# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0fdplvpcl3l3vlx1ncq6lbpqmy23mmyaa7b0lnf2phifmgm5078g";
    aarch64-linux = "11ajhx8d4i1qjlqr4fmwpha8r1bjrhg3f82fpvcj7g3kksi7b9dr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.12/alien-invasion_1.0.12_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.12/alien-invasion_1.0.12_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "alien-invasion";
  version = "1.0.12";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./alien-invasion $out/bin/alien-invasion
  '';

  meta = {
    description = "An alien invasion simulation tool";
    homepage = "https://github.com/darkfronza/alien-invasion";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
