# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0l6asprnnf03xmzk54dj52sdn1c4hpap7w5x4hg5zcgxwbikp9na";
    aarch64-linux = "109m3xpcdjm1fhxlp6ad66wkmd4j12xrrkfd1g6zh5kymll3h955";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.14/alien-invasion_1.0.14_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.14/alien-invasion_1.0.14_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "alien-invasion";
  version = "1.0.14";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./alien-invasion $out/bin/alien-invasion
  '';

  meta = {
    description = "An alien invasion simulation tool";
    homepage = "https://github.com/darkfronza/alien-invasion";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
