# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "15ig1rsan72fvgdl64j7zbd0j10l8a2v6byh9msk5ayszq86g159";
    aarch64-linux = "01hk2jhaqnpasxsjlicw7nww6w6ax65h11gybn2dj1347zvy39na";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.9/alien-invasion_1.0.9_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.9/alien-invasion_1.0.9_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "alien-invasion";
  version = "1.0.9";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./alien-invasion $out/bin/alien-invasion
  '';

  meta = {
    description = "An alien invasion simulation tool";
    homepage = "https://github.com/darkfronza/alien-invasion";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
