# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "18r3myfp83i88s3s735ryzr7z6z0cqpmf2d26qwka84ni0wbkhgn";
    aarch64-linux = "1b2zzcxqbwzbcvs6w7pv8xwa5z2578q22pddbafgif1fgybip36w";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.15/alien-invasion_1.0.15_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.15/alien-invasion_1.0.15_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "alien-invasion";
  version = "1.0.15";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./alien-invasion $out/bin/alien-invasion
  '';

  meta = {
    description = "An alien invasion simulation tool";
    homepage = "https://github.com/darkfronza/alien-invasion";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
