# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "15kq6pz61cxigp65vv28x87h004yr463y8r035jhdk5q3236902r";
    aarch64-linux = "0jfxkpllbznm2mxizab98ii2d8pd558995g51d3s4w8f142vi80s";
  };

  urlMap = {
    x86_64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.4/alien-invasion_1.0.4_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/darkfronza/alien-invasion/releases/download/v1.0.4/alien-invasion_1.0.4_linux_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "alien-invasion";
  version = "1.0.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./alien-invasion $out/bin/alien-invasion
  '';

  meta = {
    description = "An alien invasion simulation tool";
    homepage = "https://github.com/darkfronza/alien-invasion";
    license = lib.licenses.gpl3Only;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-linux"
      "x86_64-linux"
    ];
  };
}
